export * from './delete-leads-property'
export * from './get-leads-property'
export * from './patch-leads-property'
export * from './post-leads-property'
export * from './search-leads-property'
export * from './sort-leads-property'
export * from './get-total-leads-property'